/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardPatientsRouteImport } from './routes/dashboard/patients'
import { Route as DashboardMisdiagnosisSolutionRouteImport } from './routes/dashboard/misdiagnosis-solution'
import { Route as DashboardCallsRouteImport } from './routes/dashboard/calls'
import { Route as DashboardAlertsRouteImport } from './routes/dashboard/alerts'
import { Route as DashboardAgentsRouteImport } from './routes/dashboard/agents'
import { Route as DashboardPatientsAddRouteImport } from './routes/dashboard/patients.add'
import { Route as DashboardPatientsIdRouteImport } from './routes/dashboard/patients.$id'
import { Route as DashboardCallsSimulateRouteImport } from './routes/dashboard/calls.simulate'
import { Route as DashboardCallsIdRouteImport } from './routes/dashboard/calls.$id'
import { Route as DashboardAgentsCreateRouteImport } from './routes/dashboard/agents.create'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPatientsRoute = DashboardPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMisdiagnosisSolutionRoute =
  DashboardMisdiagnosisSolutionRouteImport.update({
    id: '/misdiagnosis-solution',
    path: '/misdiagnosis-solution',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCallsRoute = DashboardCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsRoute = DashboardAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPatientsAddRoute = DashboardPatientsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => DashboardPatientsRoute,
} as any)
const DashboardPatientsIdRoute = DashboardPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardPatientsRoute,
} as any)
const DashboardCallsSimulateRoute = DashboardCallsSimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => DashboardCallsRoute,
} as any)
const DashboardCallsIdRoute = DashboardCallsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardCallsRoute,
} as any)
const DashboardAgentsCreateRoute = DashboardAgentsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => DashboardAgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/agents': typeof DashboardAgentsRouteWithChildren
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/calls': typeof DashboardCallsRouteWithChildren
  '/dashboard/misdiagnosis-solution': typeof DashboardMisdiagnosisSolutionRoute
  '/dashboard/patients': typeof DashboardPatientsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/agents/create': typeof DashboardAgentsCreateRoute
  '/dashboard/calls/$id': typeof DashboardCallsIdRoute
  '/dashboard/calls/simulate': typeof DashboardCallsSimulateRoute
  '/dashboard/patients/$id': typeof DashboardPatientsIdRoute
  '/dashboard/patients/add': typeof DashboardPatientsAddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/agents': typeof DashboardAgentsRouteWithChildren
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/calls': typeof DashboardCallsRouteWithChildren
  '/dashboard/misdiagnosis-solution': typeof DashboardMisdiagnosisSolutionRoute
  '/dashboard/patients': typeof DashboardPatientsRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/agents/create': typeof DashboardAgentsCreateRoute
  '/dashboard/calls/$id': typeof DashboardCallsIdRoute
  '/dashboard/calls/simulate': typeof DashboardCallsSimulateRoute
  '/dashboard/patients/$id': typeof DashboardPatientsIdRoute
  '/dashboard/patients/add': typeof DashboardPatientsAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/agents': typeof DashboardAgentsRouteWithChildren
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/calls': typeof DashboardCallsRouteWithChildren
  '/dashboard/misdiagnosis-solution': typeof DashboardMisdiagnosisSolutionRoute
  '/dashboard/patients': typeof DashboardPatientsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/agents/create': typeof DashboardAgentsCreateRoute
  '/dashboard/calls/$id': typeof DashboardCallsIdRoute
  '/dashboard/calls/simulate': typeof DashboardCallsSimulateRoute
  '/dashboard/patients/$id': typeof DashboardPatientsIdRoute
  '/dashboard/patients/add': typeof DashboardPatientsAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/agents'
    | '/dashboard/alerts'
    | '/dashboard/calls'
    | '/dashboard/misdiagnosis-solution'
    | '/dashboard/patients'
    | '/dashboard/'
    | '/dashboard/agents/create'
    | '/dashboard/calls/$id'
    | '/dashboard/calls/simulate'
    | '/dashboard/patients/$id'
    | '/dashboard/patients/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/agents'
    | '/dashboard/alerts'
    | '/dashboard/calls'
    | '/dashboard/misdiagnosis-solution'
    | '/dashboard/patients'
    | '/dashboard'
    | '/dashboard/agents/create'
    | '/dashboard/calls/$id'
    | '/dashboard/calls/simulate'
    | '/dashboard/patients/$id'
    | '/dashboard/patients/add'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/agents'
    | '/dashboard/alerts'
    | '/dashboard/calls'
    | '/dashboard/misdiagnosis-solution'
    | '/dashboard/patients'
    | '/dashboard/'
    | '/dashboard/agents/create'
    | '/dashboard/calls/$id'
    | '/dashboard/calls/simulate'
    | '/dashboard/patients/$id'
    | '/dashboard/patients/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients': {
      id: '/dashboard/patients'
      path: '/patients'
      fullPath: '/dashboard/patients'
      preLoaderRoute: typeof DashboardPatientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/misdiagnosis-solution': {
      id: '/dashboard/misdiagnosis-solution'
      path: '/misdiagnosis-solution'
      fullPath: '/dashboard/misdiagnosis-solution'
      preLoaderRoute: typeof DashboardMisdiagnosisSolutionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calls': {
      id: '/dashboard/calls'
      path: '/calls'
      fullPath: '/dashboard/calls'
      preLoaderRoute: typeof DashboardCallsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/alerts': {
      id: '/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agents': {
      id: '/dashboard/agents'
      path: '/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof DashboardAgentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients/add': {
      id: '/dashboard/patients/add'
      path: '/add'
      fullPath: '/dashboard/patients/add'
      preLoaderRoute: typeof DashboardPatientsAddRouteImport
      parentRoute: typeof DashboardPatientsRoute
    }
    '/dashboard/patients/$id': {
      id: '/dashboard/patients/$id'
      path: '/$id'
      fullPath: '/dashboard/patients/$id'
      preLoaderRoute: typeof DashboardPatientsIdRouteImport
      parentRoute: typeof DashboardPatientsRoute
    }
    '/dashboard/calls/simulate': {
      id: '/dashboard/calls/simulate'
      path: '/simulate'
      fullPath: '/dashboard/calls/simulate'
      preLoaderRoute: typeof DashboardCallsSimulateRouteImport
      parentRoute: typeof DashboardCallsRoute
    }
    '/dashboard/calls/$id': {
      id: '/dashboard/calls/$id'
      path: '/$id'
      fullPath: '/dashboard/calls/$id'
      preLoaderRoute: typeof DashboardCallsIdRouteImport
      parentRoute: typeof DashboardCallsRoute
    }
    '/dashboard/agents/create': {
      id: '/dashboard/agents/create'
      path: '/create'
      fullPath: '/dashboard/agents/create'
      preLoaderRoute: typeof DashboardAgentsCreateRouteImport
      parentRoute: typeof DashboardAgentsRoute
    }
  }
}

interface DashboardAgentsRouteChildren {
  DashboardAgentsCreateRoute: typeof DashboardAgentsCreateRoute
}

const DashboardAgentsRouteChildren: DashboardAgentsRouteChildren = {
  DashboardAgentsCreateRoute: DashboardAgentsCreateRoute,
}

const DashboardAgentsRouteWithChildren = DashboardAgentsRoute._addFileChildren(
  DashboardAgentsRouteChildren,
)

interface DashboardCallsRouteChildren {
  DashboardCallsIdRoute: typeof DashboardCallsIdRoute
  DashboardCallsSimulateRoute: typeof DashboardCallsSimulateRoute
}

const DashboardCallsRouteChildren: DashboardCallsRouteChildren = {
  DashboardCallsIdRoute: DashboardCallsIdRoute,
  DashboardCallsSimulateRoute: DashboardCallsSimulateRoute,
}

const DashboardCallsRouteWithChildren = DashboardCallsRoute._addFileChildren(
  DashboardCallsRouteChildren,
)

interface DashboardPatientsRouteChildren {
  DashboardPatientsIdRoute: typeof DashboardPatientsIdRoute
  DashboardPatientsAddRoute: typeof DashboardPatientsAddRoute
}

const DashboardPatientsRouteChildren: DashboardPatientsRouteChildren = {
  DashboardPatientsIdRoute: DashboardPatientsIdRoute,
  DashboardPatientsAddRoute: DashboardPatientsAddRoute,
}

const DashboardPatientsRouteWithChildren =
  DashboardPatientsRoute._addFileChildren(DashboardPatientsRouteChildren)

interface DashboardRouteChildren {
  DashboardAgentsRoute: typeof DashboardAgentsRouteWithChildren
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardCallsRoute: typeof DashboardCallsRouteWithChildren
  DashboardMisdiagnosisSolutionRoute: typeof DashboardMisdiagnosisSolutionRoute
  DashboardPatientsRoute: typeof DashboardPatientsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgentsRoute: DashboardAgentsRouteWithChildren,
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardCallsRoute: DashboardCallsRouteWithChildren,
  DashboardMisdiagnosisSolutionRoute: DashboardMisdiagnosisSolutionRoute,
  DashboardPatientsRoute: DashboardPatientsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
